name: Zipline CI (macOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # use latest v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install TA lib (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install ta-lib
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-py${{matrix.python-version}}-${{ hashFiles(env.PIP_CONSTRAINT) }}
        restore-keys: |
          ${{ runner.os }}-pip-py${{matrix.python-version}}-
    - name: Install scientific python requirements
      run: |
        conda install -c conda-forge pip pandas=0.22.0 numpy=1.19.1 scipy=1.5.0 cython=0.29.21 bcolz=1.2.1
    - name: Install requirements
      run: |
        pip install -e .[dev]
    - name: Run tests
      run: |
        nosetests tests