- name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: custom-dir/
        
